version: '3.5'

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /docker/ssl:/etc/nginx/ssl
    depends_on:
      - zabbix-web-nginx-pgsql
    networks:
      - zbx_net_frontend
    deploy:
      mode: replicated
      replicas: 1

networks:
  zbx_net_frontend:
    external: true
