version: '3.5'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - ./env_file/GF_SECURITY_ADMIN_PASSWORD
    networks:
      - grafana_net_backend
      - grafana_net_frontend
    volumes:
      - grafana_data:/var/lib/grafana  # Persist Grafana data

networks:
  grafana_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.0/24

  grafana_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.101.0/24

  zbx_net_backend:
    external: true

volumes:
  grafana_data:
